Modernize build (to Hatch)
eclipse/paho.mqtt.python pull request #774
Opened 2023-12-21 11:08 UTC by akx

2023-12-21 11:23 UTC, akx commented
Hey @ofek, if you have time to take a peek – I think I'm getting something hopelessly wrong with the src layout stuff if `python -m build .` is complaining

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchling)
* Getting build dependencies for wheel...
* Building wheel...
OSError: Error getting the version from source `regex`: file does not exist: src/paho/mqtt/__init__.py
```

I kinda understand that since the `src/` directory isn't there in the sdist anymore, but I think I'm Doing It Wrong here 😁

2023-12-21 14:35 UTC, ofek requested changes

2023-12-21 14:35 UTC, ofek commented on pyproject.toml
> +sources = ["src"]
```suggestion
```

2023-12-21 14:35 UTC, ofek commented on pyproject.toml
> +include = [
```suggestion
packages = [
```

2023-12-21 14:37 UTC, akx commented
Thanks @ofek ❤️

2023-12-21 14:43 UTC, ofek commented
Happy to help! Thanks for using your free time to update projects 😄

2023-12-23 10:31 UTC, akx commented
@PierreF Rebased, ready for review.

2023-12-23 16:08 UTC, PierreF commented on pyproject.toml
> +    "epl-v10",
```suggestion
    "epl-v20",
```

To match change done in #635

2023-12-23 17:52 UTC, PierreF approved these changes

2023-12-23 17:52 UTC, merged

2023-12-23 18:01 UTC, PierreF commented
Thank for this work. Also thank @cclauss  and @semuadmin for the other PR on the same subject.